name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-analysis:
    name: Runs Detekt for static code analysis
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Running Detekt
        run: bash ./gradlew detekt
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v1
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Run Unit tests
            run: bash ./gradlew test --stacktrace

  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: SonarCloud Scan
        run: bash ./gradlew jacocoUnitTestReport sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Link to SonarCloud Report
        run: echo "https://sonarcloud.io/dashboard?id=denisgasparoto_chuck-norris-facts"
