name: Android CI

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches: [ master ]

jobs:

  sonar-cloud:
    name: Runs SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Running SonarCloud Scan
        run: bash ./gradlew clean build jacocoUnitTestReport sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Link to SonarCloud Report
        run: echo "https://sonarcloud.io/dashboard?id=com.denisgasparoto.chucknorrisfacts"
