name: Android CI

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    branches: [ master ]

jobs:
  code-analysis:
    name: Runs Detekt
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Running Detekt
        run: bash ./gradlew detekt

  unit-tests:
    name: Runs Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

  codacy-analysis-cli:
    runs-on: ubuntu-latest
    name: codacy-analysis-cli
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: mrfyda/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
